/** Curated ISO 3166-2 subdivision examples; this is deliberately not a global-complete dataset. */
export const countryStateDataSource = Object.freeze({
  name: 'Curated ISO 3166-2 subdivision examples',
  standard: 'ISO 3166-2 code format; per-country coverage varies',
  coverage:
    'Selected subdivisions for Indonesia, United States, and additional ASEAN markets; not complete worldwide',
  verifiedDate: '2026-10-04',
});

export interface CountrySubdivision {
  countryCode: string;
  code: string;
  name: string;
  type?: string;
}

export const countryStates: CountrySubdivision[] = [
  // ==========================================
  // --- INDONESIA (ID) - 38 Provinces (ISO 3166-2:ID) ---
  // ==========================================
  { countryCode: 'ID', code: 'ID-AC', name: 'Aceh', type: 'province' },
  { countryCode: 'ID', code: 'ID-BA', name: 'Bali', type: 'province' },
  { countryCode: 'ID', code: 'ID-BB', name: 'Kepulauan Bangka Belitung', type: 'province' },
  { countryCode: 'ID', code: 'ID-BT', name: 'Banten', type: 'province' },
  { countryCode: 'ID', code: 'ID-BE', name: 'Bengkulu', type: 'province' },
  { countryCode: 'ID', code: 'ID-GO', name: 'Gorontalo', type: 'province' },
  { countryCode: 'ID', code: 'ID-JK', name: 'DKI Jakarta', type: 'special_capital_region' },
  { countryCode: 'ID', code: 'ID-JA', name: 'Jambi', type: 'province' },
  { countryCode: 'ID', code: 'ID-JB', name: 'Jawa Barat', type: 'province' },
  { countryCode: 'ID', code: 'ID-JT', name: 'Jawa Tengah', type: 'province' },
  { countryCode: 'ID', code: 'ID-JI', name: 'Jawa Timur', type: 'province' },
  { countryCode: 'ID', code: 'ID-KB', name: 'Kalimantan Barat', type: 'province' },
  { countryCode: 'ID', code: 'ID-KS', name: 'Kalimantan Selatan', type: 'province' },
  { countryCode: 'ID', code: 'ID-KT', name: 'Kalimantan Tengah', type: 'province' },
  { countryCode: 'ID', code: 'ID-KI', name: 'Kalimantan Timur', type: 'province' },
  { countryCode: 'ID', code: 'ID-KU', name: 'Kalimantan Utara', type: 'province' },
  { countryCode: 'ID', code: 'ID-KR', name: 'Kepulauan Riau', type: 'province' },
  { countryCode: 'ID', code: 'ID-LA', name: 'Lampung', type: 'province' },
  { countryCode: 'ID', code: 'ID-MA', name: 'Maluku', type: 'province' },
  { countryCode: 'ID', code: 'ID-MU', name: 'Maluku Utara', type: 'province' },
  { countryCode: 'ID', code: 'ID-NB', name: 'Nusa Tenggara Barat', type: 'province' },
  { countryCode: 'ID', code: 'ID-NT', name: 'Nusa Tenggara Timur', type: 'province' },
  { countryCode: 'ID', code: 'ID-PA', name: 'Papua', type: 'province' },
  { countryCode: 'ID', code: 'ID-PB', name: 'Papua Barat', type: 'province' },
  { countryCode: 'ID', code: 'ID-PD', name: 'Papua Barat Daya', type: 'province' },
  { countryCode: 'ID', code: 'ID-PE', name: 'Papua Pegunungan', type: 'province' },
  { countryCode: 'ID', code: 'ID-PS', name: 'Papua Selatan', type: 'province' },
  { countryCode: 'ID', code: 'ID-PT', name: 'Papua Tengah', type: 'province' },
  { countryCode: 'ID', code: 'ID-RI', name: 'Riau', type: 'province' },
  { countryCode: 'ID', code: 'ID-SR', name: 'Sulawesi Barat', type: 'province' },
  { countryCode: 'ID', code: 'ID-SN', name: 'Sulawesi Selatan', type: 'province' },
  { countryCode: 'ID', code: 'ID-ST', name: 'Sulawesi Tengah', type: 'province' },
  { countryCode: 'ID', code: 'ID-SG', name: 'Sulawesi Tenggara', type: 'province' },
  { countryCode: 'ID', code: 'ID-SA', name: 'Sulawesi Utara', type: 'province' },
  { countryCode: 'ID', code: 'ID-SB', name: 'Sumatera Barat', type: 'province' },
  { countryCode: 'ID', code: 'ID-SS', name: 'Sumatera Selatan', type: 'province' },
  { countryCode: 'ID', code: 'ID-SU', name: 'Sumatera Utara', type: 'province' },
  { countryCode: 'ID', code: 'ID-YO', name: 'DI Yogyakarta', type: 'special_region' },

  // ==========================================
  // --- UNITED STATES (US) - 50 States + DC (ISO 3166-2:US) ---
  // ==========================================
  { countryCode: 'US', code: 'US-AL', name: 'Alabama', type: 'state' },
  { countryCode: 'US', code: 'US-AK', name: 'Alaska', type: 'state' },
  { countryCode: 'US', code: 'US-AZ', name: 'Arizona', type: 'state' },
  { countryCode: 'US', code: 'US-AR', name: 'Arkansas', type: 'state' },
  { countryCode: 'US', code: 'US-CA', name: 'California', type: 'state' },
  { countryCode: 'US', code: 'US-CO', name: 'Colorado', type: 'state' },
  { countryCode: 'US', code: 'US-CT', name: 'Connecticut', type: 'state' },
  { countryCode: 'US', code: 'US-DE', name: 'Delaware', type: 'state' },
  { countryCode: 'US', code: 'US-FL', name: 'Florida', type: 'state' },
  { countryCode: 'US', code: 'US-GA', name: 'Georgia', type: 'state' },
  { countryCode: 'US', code: 'US-HI', name: 'Hawaii', type: 'state' },
  { countryCode: 'US', code: 'US-ID', name: 'Idaho', type: 'state' },
  { countryCode: 'US', code: 'US-IL', name: 'Illinois', type: 'state' },
  { countryCode: 'US', code: 'US-IN', name: 'Indiana', type: 'state' },
  { countryCode: 'US', code: 'US-IA', name: 'Iowa', type: 'state' },
  { countryCode: 'US', code: 'US-KS', name: 'Kansas', type: 'state' },
  { countryCode: 'US', code: 'US-KY', name: 'Kentucky', type: 'state' },
  { countryCode: 'US', code: 'US-LA', name: 'Louisiana', type: 'state' },
  { countryCode: 'US', code: 'US-ME', name: 'Maine', type: 'state' },
  { countryCode: 'US', code: 'US-MD', name: 'Maryland', type: 'state' },
  { countryCode: 'US', code: 'US-MA', name: 'Massachusetts', type: 'state' },
  { countryCode: 'US', code: 'US-MI', name: 'Michigan', type: 'state' },
  { countryCode: 'US', code: 'US-MN', name: 'Minnesota', type: 'state' },
  { countryCode: 'US', code: 'US-MS', name: 'Mississippi', type: 'state' },
  { countryCode: 'US', code: 'US-MO', name: 'Missouri', type: 'state' },
  { countryCode: 'US', code: 'US-MT', name: 'Montana', type: 'state' },
  { countryCode: 'US', code: 'US-NE', name: 'Nebraska', type: 'state' },
  { countryCode: 'US', code: 'US-NV', name: 'Nevada', type: 'state' },
  { countryCode: 'US', code: 'US-NH', name: 'New Hampshire', type: 'state' },
  { countryCode: 'US', code: 'US-NJ', name: 'New Jersey', type: 'state' },
  { countryCode: 'US', code: 'US-NM', name: 'New Mexico', type: 'state' },
  { countryCode: 'US', code: 'US-NY', name: 'New York', type: 'state' },
  { countryCode: 'US', code: 'US-NC', name: 'North Carolina', type: 'state' },
  { countryCode: 'US', code: 'US-ND', name: 'North Dakota', type: 'state' },
  { countryCode: 'US', code: 'US-OH', name: 'Ohio', type: 'state' },
  { countryCode: 'US', code: 'US-OK', name: 'Oklahoma', type: 'state' },
  { countryCode: 'US', code: 'US-OR', name: 'Oregon', type: 'state' },
  { countryCode: 'US', code: 'US-PA', name: 'Pennsylvania', type: 'state' },
  { countryCode: 'US', code: 'US-RI', name: 'Rhode Island', type: 'state' },
  { countryCode: 'US', code: 'US-SC', name: 'South Carolina', type: 'state' },
  { countryCode: 'US', code: 'US-SD', name: 'South Dakota', type: 'state' },
  { countryCode: 'US', code: 'US-TN', name: 'Tennessee', type: 'state' },
  { countryCode: 'US', code: 'US-TX', name: 'Texas', type: 'state' },
  { countryCode: 'US', code: 'US-UT', name: 'Utah', type: 'state' },
  { countryCode: 'US', code: 'US-VT', name: 'Vermont', type: 'state' },
  { countryCode: 'US', code: 'US-VA', name: 'Virginia', type: 'state' },
  { countryCode: 'US', code: 'US-WA', name: 'Washington', type: 'state' },
  { countryCode: 'US', code: 'US-WV', name: 'West Virginia', type: 'state' },
  { countryCode: 'US', code: 'US-WI', name: 'Wisconsin', type: 'state' },
  { countryCode: 'US', code: 'US-WY', name: 'Wyoming', type: 'state' },
  { countryCode: 'US', code: 'US-DC', name: 'District of Columbia', type: 'district' },

  // ==========================================
  // --- UNITED KINGDOM (GB) (ISO 3166-2:GB) ---
  // ==========================================
  { countryCode: 'GB', code: 'GB-ENG', name: 'England', type: 'country' },
  { countryCode: 'GB', code: 'GB-SCT', name: 'Scotland', type: 'country' },
  { countryCode: 'GB', code: 'GB-WLS', name: 'Wales', type: 'country' },
  { countryCode: 'GB', code: 'GB-NIR', name: 'Northern Ireland', type: 'country' },

  // ==========================================
  // --- CANADA (CA) (ISO 3166-2:CA) ---
  // ==========================================
  { countryCode: 'CA', code: 'CA-AB', name: 'Alberta', type: 'province' },
  { countryCode: 'CA', code: 'CA-BC', name: 'British Columbia', type: 'province' },
  { countryCode: 'CA', code: 'CA-MB', name: 'Manitoba', type: 'province' },
  { countryCode: 'CA', code: 'CA-NB', name: 'New Brunswick', type: 'province' },
  { countryCode: 'CA', code: 'CA-NL', name: 'Newfoundland and Labrador', type: 'province' },
  { countryCode: 'CA', code: 'CA-NS', name: 'Nova Scotia', type: 'province' },
  { countryCode: 'CA', code: 'CA-ON', name: 'Ontario', type: 'province' },
  { countryCode: 'CA', code: 'CA-PE', name: 'Prince Edward Island', type: 'province' },
  { countryCode: 'CA', code: 'CA-QC', name: 'Quebec', type: 'province' },
  { countryCode: 'CA', code: 'CA-SK', name: 'Saskatchewan', type: 'province' },
  { countryCode: 'CA', code: 'CA-NT', name: 'Northwest Territories', type: 'territory' },
  { countryCode: 'CA', code: 'CA-NU', name: 'Nunavut', type: 'territory' },
  { countryCode: 'CA', code: 'CA-YT', name: 'Yukon', type: 'territory' },

  // ==========================================
  // --- AUSTRALIA (AU) (ISO 3166-2:AU) ---
  // ==========================================
  { countryCode: 'AU', code: 'AU-NSW', name: 'New South Wales', type: 'state' },
  { countryCode: 'AU', code: 'AU-VIC', name: 'Victoria', type: 'state' },
  { countryCode: 'AU', code: 'AU-QLD', name: 'Queensland', type: 'state' },
  { countryCode: 'AU', code: 'AU-WA', name: 'Western Australia', type: 'state' },
  { countryCode: 'AU', code: 'AU-SA', name: 'South Australia', type: 'state' },
  { countryCode: 'AU', code: 'AU-TAS', name: 'Tasmania', type: 'state' },
  { countryCode: 'AU', code: 'AU-ACT', name: 'Australian Capital Territory', type: 'territory' },
  { countryCode: 'AU', code: 'AU-NT', name: 'Northern Territory', type: 'territory' },

  // ==========================================
  // --- GERMANY (DE) - 16 Bundesländer (ISO 3166-2:DE) ---
  // ==========================================
  { countryCode: 'DE', code: 'DE-BW', name: 'Baden-Württemberg', type: 'state' },
  { countryCode: 'DE', code: 'DE-BY', name: 'Bavaria', type: 'state' },
  { countryCode: 'DE', code: 'DE-BE', name: 'Berlin', type: 'state' },
  { countryCode: 'DE', code: 'DE-BB', name: 'Brandenburg', type: 'state' },
  { countryCode: 'DE', code: 'DE-HB', name: 'Bremen', type: 'state' },
  { countryCode: 'DE', code: 'DE-HH', name: 'Hamburg', type: 'state' },
  { countryCode: 'DE', code: 'DE-HE', name: 'Hesse', type: 'state' },
  { countryCode: 'DE', code: 'DE-MV', name: 'Mecklenburg-Western Pomerania', type: 'state' },
  { countryCode: 'DE', code: 'DE-NI', name: 'Lower Saxony', type: 'state' },
  { countryCode: 'DE', code: 'DE-NW', name: 'North Rhine-Westphalia', type: 'state' },
  { countryCode: 'DE', code: 'DE-RP', name: 'Rhineland-Palatinate', type: 'state' },
  { countryCode: 'DE', code: 'DE-SL', name: 'Saarland', type: 'state' },
  { countryCode: 'DE', code: 'DE-SN', name: 'Saxony', type: 'state' },
  { countryCode: 'DE', code: 'DE-ST', name: 'Saxony-Anhalt', type: 'state' },
  { countryCode: 'DE', code: 'DE-SH', name: 'Schleswig-Holstein', type: 'state' },
  { countryCode: 'DE', code: 'DE-TH', name: 'Thuringia', type: 'state' },

  // ==========================================
  // --- FRANCE (FR) - 18 Régions (ISO 3166-2:FR) ---
  // ==========================================
  { countryCode: 'FR', code: 'FR-ARA', name: 'Auvergne-Rhône-Alpes', type: 'region' },
  { countryCode: 'FR', code: 'FR-BFC', name: 'Bourgogne-Franche-Comté', type: 'region' },
  { countryCode: 'FR', code: 'FR-BRE', name: 'Bretagne', type: 'region' },
  { countryCode: 'FR', code: 'FR-CVL', name: 'Centre-Val de Loire', type: 'region' },
  { countryCode: 'FR', code: 'FR-COR', name: 'Corse', type: 'region' },
  { countryCode: 'FR', code: 'FR-GES', name: 'Grand Est', type: 'region' },
  { countryCode: 'FR', code: 'FR-HDF', name: 'Hauts-de-France', type: 'region' },
  { countryCode: 'FR', code: 'FR-IDF', name: 'Île-de-France', type: 'region' },
  { countryCode: 'FR', code: 'FR-NOR', name: 'Normandie', type: 'region' },
  { countryCode: 'FR', code: 'FR-NAQ', name: 'Nouvelle-Aquitaine', type: 'region' },
  { countryCode: 'FR', code: 'FR-OCC', name: 'Occitanie', type: 'region' },
  { countryCode: 'FR', code: 'FR-PDL', name: 'Pays de la Loire', type: 'region' },
  { countryCode: 'FR', code: 'FR-PAC', name: "Provence-Alpes-Côte d'Azur", type: 'region' },
  { countryCode: 'FR', code: 'FR-GP', name: 'Guadeloupe', type: 'overseas_region' },
  { countryCode: 'FR', code: 'FR-MQ', name: 'Martinique', type: 'overseas_region' },
  { countryCode: 'FR', code: 'FR-GF', name: 'Guyane', type: 'overseas_region' },
  { countryCode: 'FR', code: 'FR-RE', name: 'La Réunion', type: 'overseas_region' },
  { countryCode: 'FR', code: 'FR-YT', name: 'Mayotte', type: 'overseas_region' },

  // ==========================================
  // --- ITALY (IT) - 20 Regioni (ISO 3166-2:IT) ---
  // ==========================================
  { countryCode: 'IT', code: 'IT-65', name: 'Abruzzo', type: 'region' },
  { countryCode: 'IT', code: 'IT-77', name: 'Basilicata', type: 'region' },
  { countryCode: 'IT', code: 'IT-78', name: 'Calabria', type: 'region' },
  { countryCode: 'IT', code: 'IT-72', name: 'Campania', type: 'region' },
  { countryCode: 'IT', code: 'IT-45', name: 'Emilia-Romagna', type: 'region' },
  { countryCode: 'IT', code: 'IT-36', name: 'Friuli Venezia Giulia', type: 'region' },
  { countryCode: 'IT', code: 'IT-62', name: 'Lazio', type: 'region' },
  { countryCode: 'IT', code: 'IT-42', name: 'Liguria', type: 'region' },
  { countryCode: 'IT', code: 'IT-25', name: 'Lombardia', type: 'region' },
  { countryCode: 'IT', code: 'IT-57', name: 'Marche', type: 'region' },
  { countryCode: 'IT', code: 'IT-67', name: 'Molise', type: 'region' },
  { countryCode: 'IT', code: 'IT-21', name: 'Piemonte', type: 'region' },
  { countryCode: 'IT', code: 'IT-75', name: 'Puglia', type: 'region' },
  { countryCode: 'IT', code: 'IT-88', name: 'Sardegna', type: 'region' },
  { countryCode: 'IT', code: 'IT-82', name: 'Sicilia', type: 'region' },
  { countryCode: 'IT', code: 'IT-52', name: 'Toscana', type: 'region' },
  { countryCode: 'IT', code: 'IT-32', name: 'Trentino-Alto Adige', type: 'region' },
  { countryCode: 'IT', code: 'IT-55', name: 'Umbria', type: 'region' },
  { countryCode: 'IT', code: 'IT-23', name: "Valle d'Aosta", type: 'region' },
  { countryCode: 'IT', code: 'IT-34', name: 'Veneto', type: 'region' },

  // ==========================================
  // --- SPAIN (ES) - 17 Comunidades Autónomas (ISO 3166-2:ES) ---
  // ==========================================
  { countryCode: 'ES', code: 'ES-AN', name: 'Andalucía', type: 'autonomous_community' },
  { countryCode: 'ES', code: 'ES-AR', name: 'Aragón', type: 'autonomous_community' },
  {
    countryCode: 'ES',
    code: 'ES-AS',
    name: 'Principado de Asturias',
    type: 'autonomous_community',
  },
  { countryCode: 'ES', code: 'ES-IB', name: 'Islas Baleares', type: 'autonomous_community' },
  { countryCode: 'ES', code: 'ES-CN', name: 'Canarias', type: 'autonomous_community' },
  { countryCode: 'ES', code: 'ES-CB', name: 'Cantabria', type: 'autonomous_community' },
  { countryCode: 'ES', code: 'ES-CL', name: 'Castilla y León', type: 'autonomous_community' },
  { countryCode: 'ES', code: 'ES-CM', name: 'Castilla-La Mancha', type: 'autonomous_community' },
  { countryCode: 'ES', code: 'ES-CT', name: 'Cataluña', type: 'autonomous_community' },
  { countryCode: 'ES', code: 'ES-VC', name: 'Comunitat Valenciana', type: 'autonomous_community' },
  { countryCode: 'ES', code: 'ES-EX', name: 'Extremadura', type: 'autonomous_community' },
  { countryCode: 'ES', code: 'ES-GA', name: 'Galicia', type: 'autonomous_community' },
  { countryCode: 'ES', code: 'ES-MD', name: 'Comunidad de Madrid', type: 'autonomous_community' },
  { countryCode: 'ES', code: 'ES-MC', name: 'Región de Murcia', type: 'autonomous_community' },
  {
    countryCode: 'ES',
    code: 'ES-NC',
    name: 'Comunidad Foral de Navarra',
    type: 'autonomous_community',
  },
  { countryCode: 'ES', code: 'ES-PV', name: 'País Vasco', type: 'autonomous_community' },
  { countryCode: 'ES', code: 'ES-RI', name: 'La Rioja', type: 'autonomous_community' },
  { countryCode: 'ES', code: 'ES-CE', name: 'Ceuta', type: 'autonomous_city' },
  { countryCode: 'ES', code: 'ES-ML', name: 'Melilla', type: 'autonomous_city' },

  // ==========================================
  // --- NETHERLANDS (NL) - 12 Provincies (ISO 3166-2:NL) ---
  // ==========================================
  { countryCode: 'NL', code: 'NL-DR', name: 'Drenthe', type: 'province' },
  { countryCode: 'NL', code: 'NL-FL', name: 'Flevoland', type: 'province' },
  { countryCode: 'NL', code: 'NL-FR', name: 'Friesland', type: 'province' },
  { countryCode: 'NL', code: 'NL-GE', name: 'Gelderland', type: 'province' },
  { countryCode: 'NL', code: 'NL-GR', name: 'Groningen', type: 'province' },
  { countryCode: 'NL', code: 'NL-LI', name: 'Limburg', type: 'province' },
  { countryCode: 'NL', code: 'NL-NB', name: 'Noord-Brabant', type: 'province' },
  { countryCode: 'NL', code: 'NL-NH', name: 'Noord-Holland', type: 'province' },
  { countryCode: 'NL', code: 'NL-OV', name: 'Overijssel', type: 'province' },
  { countryCode: 'NL', code: 'NL-UT', name: 'Utrecht', type: 'province' },
  { countryCode: 'NL', code: 'NL-ZE', name: 'Zeeland', type: 'province' },
  { countryCode: 'NL', code: 'NL-ZH', name: 'Zuid-Holland', type: 'province' },

  // ==========================================
  // --- MALAYSIA (MY) (ISO 3166-2:MY) ---
  // ==========================================
  { countryCode: 'MY', code: 'MY-JHR', name: 'Johor', type: 'state' },
  { countryCode: 'MY', code: 'MY-KDH', name: 'Kedah', type: 'state' },
  { countryCode: 'MY', code: 'MY-KTN', name: 'Kelantan', type: 'state' },
  { countryCode: 'MY', code: 'MY-MLK', name: 'Melaka', type: 'state' },
  { countryCode: 'MY', code: 'MY-NSN', name: 'Negeri Sembilan', type: 'state' },
  { countryCode: 'MY', code: 'MY-PHG', name: 'Pahang', type: 'state' },
  { countryCode: 'MY', code: 'MY-PRK', name: 'Perak', type: 'state' },
  { countryCode: 'MY', code: 'MY-PLS', name: 'Perlis', type: 'state' },
  { countryCode: 'MY', code: 'MY-PNG', name: 'Pulau Pinang', type: 'state' },
  { countryCode: 'MY', code: 'MY-SBH', name: 'Sabah', type: 'state' },
  { countryCode: 'MY', code: 'MY-SWK', name: 'Sarawak', type: 'state' },
  { countryCode: 'MY', code: 'MY-SGR', name: 'Selangor', type: 'state' },
  { countryCode: 'MY', code: 'MY-TRG', name: 'Terengganu', type: 'state' },
  {
    countryCode: 'MY',
    code: 'MY-KUL',
    name: 'Wilayah Persekutuan Kuala Lumpur',
    type: 'federal_territory',
  },
  {
    countryCode: 'MY',
    code: 'MY-LBN',
    name: 'Wilayah Persekutuan Labuan',
    type: 'federal_territory',
  },
  {
    countryCode: 'MY',
    code: 'MY-PJY',
    name: 'Wilayah Persekutuan Putrajaya',
    type: 'federal_territory',
  },

  // ==========================================
  // --- SINGAPORE (SG) (ISO 3166-2:SG) ---
  // ==========================================
  { countryCode: 'SG', code: 'SG-CS', name: 'Central Singapore', type: 'district' },
  { countryCode: 'SG', code: 'SG-NE', name: 'North East', type: 'district' },
  { countryCode: 'SG', code: 'SG-NW', name: 'North West', type: 'district' },
  { countryCode: 'SG', code: 'SG-SE', name: 'South East', type: 'district' },
  { countryCode: 'SG', code: 'SG-SW', name: 'South West', type: 'district' },

  // ==========================================
  // --- JAPAN (JP) - 47 Prefectures (ISO 3166-2:JP) ---
  // ==========================================
  { countryCode: 'JP', code: 'JP-01', name: 'Hokkaido', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-02', name: 'Aomori', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-03', name: 'Iwate', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-04', name: 'Miyagi', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-05', name: 'Akita', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-06', name: 'Yamagata', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-07', name: 'Fukushima', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-08', name: 'Ibaraki', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-09', name: 'Tochigi', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-10', name: 'Gunma', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-11', name: 'Saitama', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-12', name: 'Chiba', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-13', name: 'Tokyo', type: 'metropolis' },
  { countryCode: 'JP', code: 'JP-14', name: 'Kanagawa', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-15', name: 'Niigata', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-16', name: 'Toyama', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-17', name: 'Ishikawa', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-18', name: 'Fukui', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-19', name: 'Yamanashi', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-20', name: 'Nagano', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-21', name: 'Gifu', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-22', name: 'Shizuoka', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-23', name: 'Aichi', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-24', name: 'Mie', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-25', name: 'Shiga', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-26', name: 'Kyoto', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-27', name: 'Osaka', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-28', name: 'Hyogo', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-29', name: 'Nara', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-30', name: 'Wakayama', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-31', name: 'Tottori', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-32', name: 'Shimane', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-33', name: 'Okayama', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-34', name: 'Hiroshima', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-35', name: 'Yamaguchi', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-36', name: 'Tokushima', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-37', name: 'Kagawa', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-38', name: 'Ehime', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-39', name: 'Kochi', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-40', name: 'Fukuoka', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-41', name: 'Saga', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-42', name: 'Nagasaki', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-43', name: 'Kumamoto', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-44', name: 'Oita', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-45', name: 'Miyazaki', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-46', name: 'Kagoshima', type: 'prefecture' },
  { countryCode: 'JP', code: 'JP-47', name: 'Okinawa', type: 'prefecture' },

  // ==========================================
  // --- CHINA (CN) - 34 Provincial Divisions (ISO 3166-2:CN) ---
  // ==========================================
  { countryCode: 'CN', code: 'CN-BJ', name: 'Beijing', type: 'municipality' },
  { countryCode: 'CN', code: 'CN-SH', name: 'Shanghai', type: 'municipality' },
  { countryCode: 'CN', code: 'CN-TJ', name: 'Tianjin', type: 'municipality' },
  { countryCode: 'CN', code: 'CN-CQ', name: 'Chongqing', type: 'municipality' },
  { countryCode: 'CN', code: 'CN-GD', name: 'Guangdong', type: 'province' },
  { countryCode: 'CN', code: 'CN-ZJ', name: 'Zhejiang', type: 'province' },
  { countryCode: 'CN', code: 'CN-JS', name: 'Jiangsu', type: 'province' },
  { countryCode: 'CN', code: 'CN-SD', name: 'Shandong', type: 'province' },
  { countryCode: 'CN', code: 'CN-SC', name: 'Sichuan', type: 'province' },
  { countryCode: 'CN', code: 'CN-HB', name: 'Hubei', type: 'province' },
  { countryCode: 'CN', code: 'CN-HN', name: 'Hunan', type: 'province' },
  { countryCode: 'CN', code: 'CN-FJ', name: 'Fujian', type: 'province' },
  { countryCode: 'CN', code: 'CN-HE', name: 'Hebei', type: 'province' },
  { countryCode: 'CN', code: 'CN-HA', name: 'Henan', type: 'province' },
  { countryCode: 'CN', code: 'CN-AH', name: 'Anhui', type: 'province' },
  { countryCode: 'CN', code: 'CN-LN', name: 'Liaoning', type: 'province' },
  { countryCode: 'CN', code: 'CN-SN', name: 'Shaanxi', type: 'province' },
  { countryCode: 'CN', code: 'CN-JX', name: 'Jiangxi', type: 'province' },
  { countryCode: 'CN', code: 'CN-GX', name: 'Guangxi', type: 'autonomous_region' },
  { countryCode: 'CN', code: 'CN-YN', name: 'Yunnan', type: 'province' },
  { countryCode: 'CN', code: 'CN-HL', name: 'Heilongjiang', type: 'province' },
  { countryCode: 'CN', code: 'CN-JL', name: 'Jilin', type: 'province' },
  { countryCode: 'CN', code: 'CN-SX', name: 'Shanxi', type: 'province' },
  { countryCode: 'CN', code: 'CN-GZ', name: 'Guizhou', type: 'province' },
  { countryCode: 'CN', code: 'CN-GS', name: 'Gansu', type: 'province' },
  { countryCode: 'CN', code: 'CN-HI', name: 'Hainan', type: 'province' },
  { countryCode: 'CN', code: 'CN-NX', name: 'Ningxia', type: 'autonomous_region' },
  { countryCode: 'CN', code: 'CN-QH', name: 'Qinghai', type: 'province' },
  { countryCode: 'CN', code: 'CN-XJ', name: 'Xinjiang', type: 'autonomous_region' },
  { countryCode: 'CN', code: 'CN-NM', name: 'Inner Mongolia', type: 'autonomous_region' },
  { countryCode: 'CN', code: 'CN-XZ', name: 'Tibet', type: 'autonomous_region' },
  { countryCode: 'CN', code: 'CN-HK', name: 'Hong Kong', type: 'special_administrative_region' },
  { countryCode: 'CN', code: 'CN-MO', name: 'Macau', type: 'special_administrative_region' },
  { countryCode: 'CN', code: 'CN-TW', name: 'Taiwan', type: 'province' },

  // ==========================================
  // --- INDIA (IN) - 28 States & 8 UTs (ISO 3166-2:IN) ---
  // ==========================================
  { countryCode: 'IN', code: 'IN-MH', name: 'Maharashtra', type: 'state' },
  { countryCode: 'IN', code: 'IN-DL', name: 'Delhi', type: 'union_territory' },
  { countryCode: 'IN', code: 'IN-KA', name: 'Karnataka', type: 'state' },
  { countryCode: 'IN', code: 'IN-TN', name: 'Tamil Nadu', type: 'state' },
  { countryCode: 'IN', code: 'IN-GJ', name: 'Gujarat', type: 'state' },
  { countryCode: 'IN', code: 'IN-UP', name: 'Uttar Pradesh', type: 'state' },
  { countryCode: 'IN', code: 'IN-TG', name: 'Telangana', type: 'state' },
  { countryCode: 'IN', code: 'IN-WB', name: 'West Bengal', type: 'state' },
  { countryCode: 'IN', code: 'IN-RJ', name: 'Rajasthan', type: 'state' },
  { countryCode: 'IN', code: 'IN-AP', name: 'Andhra Pradesh', type: 'state' },
  { countryCode: 'IN', code: 'IN-KL', name: 'Kerala', type: 'state' },
  { countryCode: 'IN', code: 'IN-MP', name: 'Madhya Pradesh', type: 'state' },
  { countryCode: 'IN', code: 'IN-PB', name: 'Punjab', type: 'state' },
  { countryCode: 'IN', code: 'IN-HR', name: 'Haryana', type: 'state' },
  { countryCode: 'IN', code: 'IN-BR', name: 'Bihar', type: 'state' },
  { countryCode: 'IN', code: 'IN-OR', name: 'Odisha', type: 'state' },
  { countryCode: 'IN', code: 'IN-AS', name: 'Assam', type: 'state' },
  { countryCode: 'IN', code: 'IN-JH', name: 'Jharkhand', type: 'state' },
  { countryCode: 'IN', code: 'IN-CT', name: 'Chhattisgarh', type: 'state' },
  { countryCode: 'IN', code: 'IN-UT', name: 'Uttarakhand', type: 'state' },
  { countryCode: 'IN', code: 'IN-HP', name: 'Himachal Pradesh', type: 'state' },
  { countryCode: 'IN', code: 'IN-GA', name: 'Goa', type: 'state' },
  { countryCode: 'IN', code: 'IN-TR', name: 'Tripura', type: 'state' },
  { countryCode: 'IN', code: 'IN-MN', name: 'Manipur', type: 'state' },
  { countryCode: 'IN', code: 'IN-ML', name: 'Meghalaya', type: 'state' },
  { countryCode: 'IN', code: 'IN-NL', name: 'Nagaland', type: 'state' },
  { countryCode: 'IN', code: 'IN-MZ', name: 'Mizoram', type: 'state' },
  { countryCode: 'IN', code: 'IN-SK', name: 'Sikkim', type: 'state' },
  { countryCode: 'IN', code: 'IN-AR', name: 'Arunachal Pradesh', type: 'state' },
  { countryCode: 'IN', code: 'IN-JK', name: 'Jammu and Kashmir', type: 'union_territory' },
  { countryCode: 'IN', code: 'IN-LA', name: 'Ladakh', type: 'union_territory' },
  { countryCode: 'IN', code: 'IN-PY', name: 'Puducherry', type: 'union_territory' },
  { countryCode: 'IN', code: 'IN-CH', name: 'Chandigarh', type: 'union_territory' },
  {
    countryCode: 'IN',
    code: 'IN-AN',
    name: 'Andaman and Nicobar Islands',
    type: 'union_territory',
  },
  {
    countryCode: 'IN',
    code: 'IN-DH',
    name: 'Dadra and Nagar Haveli and Daman and Diu',
    type: 'union_territory',
  },
  { countryCode: 'IN', code: 'IN-LD', name: 'Lakshadweep', type: 'union_territory' },

  // ==========================================
  // --- BRAZIL (BR) - 27 Estados (ISO 3166-2:BR) ---
  // ==========================================
  { countryCode: 'BR', code: 'BR-SP', name: 'São Paulo', type: 'state' },
  { countryCode: 'BR', code: 'BR-RJ', name: 'Rio de Janeiro', type: 'state' },
  { countryCode: 'BR', code: 'BR-MG', name: 'Minas Gerais', type: 'state' },
  { countryCode: 'BR', code: 'BR-BA', name: 'Bahia', type: 'state' },
  { countryCode: 'BR', code: 'BR-PR', name: 'Paraná', type: 'state' },
  { countryCode: 'BR', code: 'BR-RS', name: 'Rio Grande do Sul', type: 'state' },
  { countryCode: 'BR', code: 'BR-PE', name: 'Pernambuco', type: 'state' },
  { countryCode: 'BR', code: 'BR-CE', name: 'Ceará', type: 'state' },
  { countryCode: 'BR', code: 'BR-PA', name: 'Pará', type: 'state' },
  { countryCode: 'BR', code: 'BR-SC', name: 'Santa Catarina', type: 'state' },
  { countryCode: 'BR', code: 'BR-GO', name: 'Goiás', type: 'state' },
  { countryCode: 'BR', code: 'BR-MA', name: 'Maranhão', type: 'state' },
  { countryCode: 'BR', code: 'BR-AM', name: 'Amazonas', type: 'state' },
  { countryCode: 'BR', code: 'BR-ES', name: 'Espírito Santo', type: 'state' },
  { countryCode: 'BR', code: 'BR-PB', name: 'Paraíba', type: 'state' },
  { countryCode: 'BR', code: 'BR-MT', name: 'Mato Grosso', type: 'state' },
  { countryCode: 'BR', code: 'BR-RN', name: 'Rio Grande do Norte', type: 'state' },
  { countryCode: 'BR', code: 'BR-AL', name: 'Alagoas', type: 'state' },
  { countryCode: 'BR', code: 'BR-PI', name: 'Piauí', type: 'state' },
  { countryCode: 'BR', code: 'BR-DF', name: 'Distrito Federal', type: 'federal_district' },
  { countryCode: 'BR', code: 'BR-MS', name: 'Mato Grosso do Sul', type: 'state' },
  { countryCode: 'BR', code: 'BR-SE', name: 'Sergipe', type: 'state' },
  { countryCode: 'BR', code: 'BR-RO', name: 'Rondônia', type: 'state' },
  { countryCode: 'BR', code: 'BR-TO', name: 'Tocantins', type: 'state' },
  { countryCode: 'BR', code: 'BR-AC', name: 'Acre', type: 'state' },
  { countryCode: 'BR', code: 'BR-AP', name: 'Amapá', type: 'state' },
  { countryCode: 'BR', code: 'BR-RR', name: 'Roraima', type: 'state' },

  // ==========================================
  // --- MEXICO (MX) - 32 Estados (ISO 3166-2:MX) ---
  // ==========================================
  { countryCode: 'MX', code: 'MX-CMX', name: 'Ciudad de México', type: 'capital_city' },
  { countryCode: 'MX', code: 'MX-JAL', name: 'Jalisco', type: 'state' },
  { countryCode: 'MX', code: 'MX-NLE', name: 'Nuevo León', type: 'state' },
  { countryCode: 'MX', code: 'MX-MEX', name: 'Estado de México', type: 'state' },
  { countryCode: 'MX', code: 'MX-PUE', name: 'Puebla', type: 'state' },
  { countryCode: 'MX', code: 'MX-GUA', name: 'Guanajuato', type: 'state' },
  { countryCode: 'MX', code: 'MX-VER', name: 'Veracruz', type: 'state' },
  { countryCode: 'MX', code: 'MX-BCN', name: 'Baja California', type: 'state' },
  { countryCode: 'MX', code: 'MX-BCS', name: 'Baja California Sur', type: 'state' },
  { countryCode: 'MX', code: 'MX-CHH', name: 'Chihuahua', type: 'state' },
  { countryCode: 'MX', code: 'MX-COA', name: 'Coahuila', type: 'state' },
  { countryCode: 'MX', code: 'MX-SON', name: 'Sonora', type: 'state' },
  { countryCode: 'MX', code: 'MX-TAM', name: 'Tamaulipas', type: 'state' },
  { countryCode: 'MX', code: 'MX-SIN', name: 'Sinaloa', type: 'state' },
  { countryCode: 'MX', code: 'MX-SLP', name: 'San Luis Potosí', type: 'state' },
  { countryCode: 'MX', code: 'MX-QUE', name: 'Querétaro', type: 'state' },
  { countryCode: 'MX', code: 'MX-YUC', name: 'Yucatán', type: 'state' },
  { countryCode: 'MX', code: 'MX-ROO', name: 'Quintana Roo', type: 'state' },
  { countryCode: 'MX', code: 'MX-AGU', name: 'Aguascalientes', type: 'state' },
  { countryCode: 'MX', code: 'MX-MOR', name: 'Morelos', type: 'state' },
  { countryCode: 'MX', code: 'MX-MIC', name: 'Michoacán', type: 'state' },
  { countryCode: 'MX', code: 'MX-OAX', name: 'Oaxaca', type: 'state' },
  { countryCode: 'MX', code: 'MX-TAB', name: 'Tabasco', type: 'state' },
  { countryCode: 'MX', code: 'MX-CHP', name: 'Chiapas', type: 'state' },
  { countryCode: 'MX', code: 'MX-GRO', name: 'Guerrero', type: 'state' },
  { countryCode: 'MX', code: 'MX-DUR', name: 'Durango', type: 'state' },
  { countryCode: 'MX', code: 'MX-ZAC', name: 'Zacatecas', type: 'state' },
  { countryCode: 'MX', code: 'MX-HID', name: 'Hidalgo', type: 'state' },
  { countryCode: 'MX', code: 'MX-NAY', name: 'Nayarit', type: 'state' },
  { countryCode: 'MX', code: 'MX-TLA', name: 'Tlaxcala', type: 'state' },
  { countryCode: 'MX', code: 'MX-CAM', name: 'Campeche', type: 'state' },
  { countryCode: 'MX', code: 'MX-COL', name: 'Colima', type: 'state' },

  // ==========================================
  // --- SAUDI ARABIA (SA) - 13 Provinces (ISO 3166-2:SA) ---
  // ==========================================
  { countryCode: 'SA', code: 'SA-01', name: 'Riyadh', type: 'province' },
  { countryCode: 'SA', code: 'SA-02', name: 'Makkah', type: 'province' },
  { countryCode: 'SA', code: 'SA-04', name: 'Eastern Province', type: 'province' },
  { countryCode: 'SA', code: 'SA-03', name: 'Madinah', type: 'province' },
  { countryCode: 'SA', code: 'SA-05', name: 'Al-Qassim', type: 'province' },
  { countryCode: 'SA', code: 'SA-06', name: 'Asir', type: 'province' },
  { countryCode: 'SA', code: 'SA-07', name: 'Tabuk', type: 'province' },
  { countryCode: 'SA', code: 'SA-08', name: 'Hail', type: 'province' },
  { countryCode: 'SA', code: 'SA-09', name: 'Northern Borders', type: 'province' },
  { countryCode: 'SA', code: 'SA-10', name: 'Jazan', type: 'province' },
  { countryCode: 'SA', code: 'SA-11', name: 'Najran', type: 'province' },
  { countryCode: 'SA', code: 'SA-12', name: 'Al-Baha', type: 'province' },
  { countryCode: 'SA', code: 'SA-14', name: 'Al-Jowf', type: 'province' },

  // ==========================================
  // --- UNITED ARAB EMIRATES (AE) - 7 Emirates (ISO 3166-2:AE) ---
  // ==========================================
  { countryCode: 'AE', code: 'AE-AZ', name: 'Abu Dhabi', type: 'emirate' },
  { countryCode: 'AE', code: 'AE-DU', name: 'Dubai', type: 'emirate' },
  { countryCode: 'AE', code: 'AE-SH', name: 'Sharjah', type: 'emirate' },
  { countryCode: 'AE', code: 'AE-AJ', name: 'Ajman', type: 'emirate' },
  { countryCode: 'AE', code: 'AE-UQ', name: 'Umm Al-Quwain', type: 'emirate' },
  { countryCode: 'AE', code: 'AE-RK', name: 'Ras Al-Khaimah', type: 'emirate' },
  { countryCode: 'AE', code: 'AE-FU', name: 'Fujairah', type: 'emirate' },

  // ==========================================
  // --- THAILAND (TH) - Major Economic Provinces (ISO 3166-2:TH) ---
  // ==========================================
  { countryCode: 'TH', code: 'TH-10', name: 'Bangkok', type: 'special_administrative_area' },
  { countryCode: 'TH', code: 'TH-50', name: 'Chiang Mai', type: 'province' },
  { countryCode: 'TH', code: 'TH-83', name: 'Phuket', type: 'province' },
  { countryCode: 'TH', code: 'TH-20', name: 'Chonburi', type: 'province' },
  { countryCode: 'TH', code: 'TH-21', name: 'Rayong', type: 'province' },
  { countryCode: 'TH', code: 'TH-12', name: 'Nonthaburi', type: 'province' },
  { countryCode: 'TH', code: 'TH-13', name: 'Pathum Thani', type: 'province' },
  { countryCode: 'TH', code: 'TH-11', name: 'Samut Prakan', type: 'province' },
  { countryCode: 'TH', code: 'TH-30', name: 'Nakhon Ratchasima', type: 'province' },
  { countryCode: 'TH', code: 'TH-40', name: 'Khon Kaen', type: 'province' },

  // ==========================================
  // --- VIETNAM (VN) - Major Municipalities & Provinces (ISO 3166-2:VN) ---
  // ==========================================
  { countryCode: 'VN', code: 'VN-HN', name: 'Hanoi', type: 'municipality' },
  { countryCode: 'VN', code: 'VN-SG', name: 'Ho Chi Minh City', type: 'municipality' },
  { countryCode: 'VN', code: 'VN-DN', name: 'Da Nang', type: 'municipality' },
  { countryCode: 'VN', code: 'VN-HP', name: 'Hai Phong', type: 'municipality' },
  { countryCode: 'VN', code: 'VN-CT', name: 'Can Tho', type: 'municipality' },
  { countryCode: 'VN', code: 'VN-BD', name: 'Binh Duong', type: 'province' },
  { countryCode: 'VN', code: 'VN-DNA', name: 'Dong Nai', type: 'province' },
  { countryCode: 'VN', code: 'VN-BN', name: 'Bac Ninh', type: 'province' },
  { countryCode: 'VN', code: 'VN-VT', name: 'Ba Ria - Vung Tau', type: 'province' },
  { countryCode: 'VN', code: 'VN-QN', name: 'Quang Ninh', type: 'province' },

  // ==========================================
  // --- PHILIPPINES (PH) - Key Regions (ISO 3166-2:PH) ---
  // ==========================================
  {
    countryCode: 'PH',
    code: 'PH-00',
    name: 'National Capital Region (Metro Manila)',
    type: 'region',
  },
  { countryCode: 'PH', code: 'PH-40', name: 'Calabarzon', type: 'region' },
  { countryCode: 'PH', code: 'PH-07', name: 'Central Visayas (Cebu)', type: 'region' },
  { countryCode: 'PH', code: 'PH-03', name: 'Central Luzon', type: 'region' },
  { countryCode: 'PH', code: 'PH-11', name: 'Davao Region', type: 'region' },
  { countryCode: 'PH', code: 'PH-06', name: 'Western Visayas', type: 'region' },
  { countryCode: 'PH', code: 'PH-01', name: 'Ilocos Region', type: 'region' },
  { countryCode: 'PH', code: 'PH-10', name: 'Northern Mindanao', type: 'region' },
];
