flowchart LR
  model0["base.access_group"]
  model1["base.activity"]
  model2["base.attachment"]
  model3["base.audit_log"]
  model4["base.bank"]
  model5["base.company"]
  model6["base.company_membership"]
  model7["base.country"]
  model8["base.country_state"]
  model9["base.currency"]
  model10["base.group_membership"]
  model11["base.language"]
  model12["base.model_access"]
  model13["base.partner"]
  model14["base.partner_address"]
  model15["base.partner_bank"]
  model16["base.partner_category"]
  model17["base.partner_category_link"]
  model18["base.sequence"]
  model19["base.tag"]
  model20["base.tag_link"]
  model21["base.user"]
  model1 -->|assigned_to N:1| model21
  model4 -->|country N:1| model7
  model5 -->|country N:1| model7
  model5 -->|currency N:1| model9
  model5 -->|language N:1| model11
  model6 -->|company N:1| model5
  model6 -->|user N:1| model21
  model8 -->|country N:1| model7
  model10 -->|group N:1| model0
  model10 -->|user N:1| model21
  model12 -->|group N:1| model0
  model13 -->|company N:1| model5
  model13 -->|country N:1| model7
  model13 -->|parent N:1| model13
  model13 -->|state N:1| model8
  model14 -->|country N:1| model7
  model14 -->|partner N:1| model13
  model14 -->|state N:1| model8
  model15 -->|bank N:1| model4
  model15 -->|company N:1| model5
  model15 -->|currency N:1| model9
  model15 -->|partner N:1| model13
  model17 -->|category N:1| model16
  model17 -->|partner N:1| model13
  model20 -->|tag N:1| model19
  model21 -->|language N:1| model11
  model21 -->|partner 1:1| model13
