flowchart LR
  pkg0["@moonwitness/api"]
  pkg1["@moonwitness/assets"]
  pkg2["@moonwitness/auth"]
  pkg3["@moonwitness/board"]
  pkg4["@moonwitness/client"]
  pkg5["@moonwitness/docs"]
  pkg6["@moonwitness/eslint-config"]
  pkg7["@moonwitness/jobs"]
  pkg8["@moonwitness/logger"]
  pkg9["@moonwitness/orm"]
  pkg10["@moonwitness/orm-base"]
  pkg11["@moonwitness/orm-integration"]
  pkg12["@moonwitness/orm-notification"]
  pkg13["@moonwitness/orm-organization"]
  pkg14["@moonwitness/orm-storage"]
  pkg15["@moonwitness/orm-workflow"]
  pkg16["@moonwitness/types"]
  pkg17["@moonwitness/ui"]
  pkg18["@moonwitness/ui-catalog"]
  pkg0 -->|development| pkg4
  pkg0 -->|runtime| pkg2
  pkg0 -->|runtime| pkg7
  pkg0 -->|runtime| pkg8
  pkg0 -->|runtime| pkg9
  pkg0 -->|runtime| pkg10
  pkg0 -->|runtime| pkg11
  pkg0 -->|runtime| pkg12
  pkg0 -->|runtime| pkg13
  pkg0 -->|runtime| pkg14
  pkg0 -->|runtime| pkg15
  pkg0 -->|runtime| pkg16
  pkg2 -->|runtime| pkg9
  pkg2 -->|runtime| pkg10
  pkg3 -->|runtime| pkg4
  pkg3 -->|runtime| pkg17
  pkg5 -->|runtime| pkg1
  pkg5 -->|runtime| pkg17
  pkg7 -->|runtime| pkg9
  pkg7 -->|runtime| pkg10
  pkg9 -->|runtime| pkg16
  pkg10 -->|runtime| pkg9
  pkg11 -->|runtime| pkg7
  pkg11 -->|runtime| pkg9
  pkg11 -->|runtime| pkg10
  pkg12 -->|runtime| pkg7
  pkg12 -->|runtime| pkg9
  pkg12 -->|runtime| pkg10
  pkg13 -->|runtime| pkg9
  pkg13 -->|runtime| pkg10
  pkg14 -->|runtime| pkg9
  pkg15 -->|runtime| pkg7
  pkg15 -->|runtime| pkg9
  pkg15 -->|runtime| pkg10
  pkg18 -->|runtime| pkg17
